version: '3'
services: 
  db:
    container_name: shoes-db
    image: mysql:8.0.22
    ports: 
      - 43306:3306
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - ./my.cnf:/etc/my.cnf
